import { ThemeConfig, ThemePresetId } from '../types/theme';

export const THEME_PRESETS: Record<ThemePresetId, ThemeConfig> = {
  matcha: {
    id: 'matcha',
    name: 'Matcha Cozy',
    colors: {
      primary: '#2D5A27',
      primaryLight: '#E8F3E8',
      accent: '#6A994E',
      background: '#F4F7F2',
      surface: '#FFFFFF',
      surfaceSubtle: '#EDF2EA',
      text: '#1F2E1E',
      textSecondary: '#5A6F57',
      textMuted: '#94A691',
      border: '#DCE5D8',
      success: '#38B000',
      warning: '#FFB703',
      danger: '#D90429',
      cardGlow: 'rgba(106, 153, 78, 0.15)',
    },
    fontStyle: 'playful',
    borderStyle: 'rounded',
    borderRadius: 18,
    borderWidth: 1,
    isDark: false,
  },
  retro: {
    id: 'retro',
    name: 'Retro Arcade',
    colors: {
      primary: '#FF5722',
      primaryLight: '#3D3430',
      accent: '#FFD700',
      background: '#181A24',
      surface: '#242738',
      surfaceSubtle: '#2E3247',
      text: '#FDF0D5',
      textSecondary: '#C5CBE3',
      textMuted: '#7E85A8',
      border: '#FF5722',
      success: '#06D6A0',
      warning: '#FFD166',
      danger: '#EF476F',
      cardGlow: 'rgba(255, 87, 34, 0.25)',
    },
    fontStyle: 'mono',
    borderStyle: 'sharp',
    borderRadius: 6,
    borderWidth: 2,
    isDark: true,
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Neon',
    colors: {
      primary: '#8A2BE2',
      primaryLight: '#261C3D',
      accent: '#00F0FF',
      background: '#0B0D17',
      surface: '#141829',
      surfaceSubtle: '#1C223A',
      text: '#F0F3FC',
      textSecondary: '#9AA7C7',
      textMuted: '#5F6C8D',
      border: '#8A2BE2',
      success: '#00FF9D',
      warning: '#FFB800',
      danger: '#FF0055',
      cardGlow: 'rgba(0, 240, 255, 0.2)',
    },
    fontStyle: 'modern',
    borderStyle: 'rounded',
    borderRadius: 16,
    borderWidth: 1.5,
    isDark: true,
  },
  campus: {
    id: 'campus',
    name: 'Clean Campus',
    colors: {
      primary: '#1E293B',
      primaryLight: '#EEF2F6',
      accent: '#3B82F6',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceSubtle: '#F1F5F9',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      border: '#E2E8F0',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      cardGlow: 'rgba(59, 130, 246, 0.08)',
    },
    fontStyle: 'modern',
    borderStyle: 'rounded',
    borderRadius: 12,
    borderWidth: 1,
    isDark: false,
  },
};

export const DEFAULT_THEME = THEME_PRESETS.matcha;
